### PR TITLE
Initial copy to github

### PR DESCRIPTION
**Pull request by Schreglmann**

### CODE REVIEW

**Comment by nsams** [comment]
when copying a repository without keeping the history, please always use the Vivid Planet bot as author, like here https://github.com/vivid-planet/comet-starter/commit/e1f177493ca9abae79fae45bde2706483c740458

**Comment by Schreglmann** [comment]
@nsams @dkarnutsch  author of the commit is changed to vivid-planet-bot

**Comment by kaufmo** [comment]
do we really need versioned folders? why dont we use GIT for that?

**Comment by Schreglmann** [comment]
> do we really need versioned folders? why dont we use GIT for that?

@kaufmo Just with GIT it is quite tricky to apply something like a security update to older major versions.
Also with the transition to SSR it's necessary to be able to work on two major versions at the same time.
Because of that we decided to use one folder per major version.

**Review by dkarnutsch — APPROVED** [review]

**Review by kaufmo — APPROVED** [review]
> @kaufmo Just with GIT it is quite tricky to apply something like a security update to older major versions. 

I thought we have versioned branches for that problem? main for the cuzrrent and v1.x.x v2.x.x v3.x.x for the old ones. then it should be possible with cherrypicking/merging. I see that this is more work but then the code is also cleaner and easier to understand.

> Also with the transition to SSR it's necessary to be able to work on two major versions at the same time. Because of that we decided to use one folder per major version.

for that we use the next branch normally to work on the next major version ?


But when you all think copying code inside the repo is the better thing than it is ok for me :+1:

**Comment by dkarnutsch** [comment]
> > @kaufmo Just with GIT it is quite tricky to apply something like a security update to older major versions.
> 
> I thought we have versioned branches for that problem? main for the cuzrrent and v1.x.x v2.x.x v3.x.x for the old ones. then it should be possible with cherrypicking/merging. I see that this is more work but then the code is also cleaner and easier to understand.
> 
> > Also with the transition to SSR it's necessary to be able to work on two major versions at the same time. Because of that we decided to use one folder per major version.
> 
> for that we use the next branch normally to work on the next major version ?
> 
> But when you all think copying code inside the repo is the better thing than it is ok for me 👍

To make that work all charts must have the same version. This will result into many major version bumps without any changes due to changes in other charts.

**Comment by kaufmo** [comment]
> > > @kaufmo Just with GIT it is quite tricky to apply something like a security update to older major versions.
> > 
> > 
> > I thought we have versioned branches for that problem? main for the cuzrrent and v1.x.x v2.x.x v3.x.x for the old ones. then it should be possible with cherrypicking/merging. I see that this is more work but then the code is also cleaner and easier to understand.
> > > Also with the transition to SSR it's necessary to be able to work on two major versions at the same time. Because of that we decided to use one folder per major version.
> > 
> > 
> > for that we use the next branch normally to work on the next major version ?
> > But when you all think copying code inside the repo is the better thing than it is ok for me 👍
> 
> To make that work all charts must have the same version. This will result into many major version bumps without any changes due to changes in other charts.

yeah thats correct and we do the exact same in the comet-dxp repo so why not here to?

**Pull request merged**
